apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-worker-hugepage
spec:
  config:
    ignition:
      version: 2.2.0
  kernelArguments:
  - intel_iommu=on
  - default_hugepagesz=1GB
  - hugepagesz=1G
  - hugepages=16
