---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-nfvpe-07-bmc-secret
type: Opaque
data:
  username: cm9vdA==
  password: Y2Fsdmlu

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: openshift-nfvpe-07
spec:
  online: true
  bmc:
    address: ipmi://10.19.111.19
    credentialsName: openshift-nfvpe-07-bmc-secret
  bootMACAddress: a4:bf:01:51:7e:40
